[versions]
junit = "5.10.1"
assertj = "3.24.2"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[bundles]
junit = [ "junit-engine", "junit-params", "assertj" ]