[versions]
junit = "5.11.3"
assertj = "3.26.3"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-run = { group = "org.junit.platform", name = "junit-platform-launcher" }

assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[bundles]
junit = [ "junit-engine", "junit-params", "assertj" ]